spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.129:3306/xczx?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: root

pay:
  qrcodeurl: http://192.168.110.187:63030/orders/requestpay?payNo=%s
  alipay:
    APP_ID: 2021000122655165
    APP_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbeePaI/fjUDQCwabuwfZxqOziPsKON0ii9W93nrV+anCkSlRv7VGuToAYztTJz7RWcwyV+pzE4itscMymc46a5H31TE9rcPrv85KSzZUHGMT0mZZHaG9eYugL8ZYPhvn0NfcPlRnd+Zd9o+AlzEyyURgCHoBP8u7mK+Pp+bsEYN9iltQdAi/UVep58U9ZVmEaU5pA9/lRnyn50RS3g61qBJIL+iQH/T9LayZ72xjLUIezB+0t9l1GcC6NwHRvHN7YfVa14FY5hc4rwrTICGMhnZG5rRa17he66L4CZAYORhPlnBcECRTYBgMU+TRNOtUnLG87RJFAns6eKeXNGtLxAgMBAAECggEATllUa19o0hJew2zXNMZl7M0V4sWBwa02W3iXnY5LI9N7xC748haD7PT+NII2VSToWhBMLWBHlCftfg4x80eUe5Xdq7my5A/hRP5XxMb47MScrC6hvoZwaP4qtaoe1uBMIbb4M9ANYwEeSGBG2oVjuRCIqri4LJHdtfw0NHp2tjNYKiGo9vs2G2fjAeytHQw8AlgjIZEDwWYCXzVI6tnwOEmci4TfALn7OFP4m5ABoG11NYAzQHU+dMUmymSTsUZ0zCZ9T8ljMIzju5vSLKX4BubjQikCqvSAtbBSCZP5N61gFH0ZOAwrKMqUCJJF/qTDONXt4KNMSGtfAxDeZ+Pn6QKBgQDkuv7eYp5PNmKcHigyTrruyzHIkPJNvmIX+YbQeDYtDKVG09I4guPFX4aIIhLU3IeqzMyqDT1a+aYJUl4yiXp4mnPIxapDb+2dt/mNE0C8uSIo6/TOGN7ojAdmPbHHVezssGtRQun0NRue+G9rLqDoHkD83TOzFffjJRX/jWiR+wKBgQCuAx/Rsbz239p7kQpnXVn4LCgGOrXV2TSDtKtgQpE1v1Iz8NDh6UWZGHByotPOSwjA2Ntm12vEKgELdEDk+TqbTd8QqC3dYV4c8htuTYtyZ49wHOQqgc/DryywciiWl+1RDR8tzRwwJbs9gBCQUz5N+lKRFwG+zm2AWCKJzIXHAwKBgAwNIjKbZZXs2qM5H4sPBOBiClxz7qBUAJ0cw5KmUsxq1yZ1MKVTmCalEtSHXxCiEe/Y3Iu1KN9rOelR0q68+ZvzH1ibuY3WDuH5eIeLVSTcaEVZsUtOmigMgLNNWtmS2GncHbtpWCRKzArDMjOmgEnaljf8e6Xa6XWpVZBiZfkTAoGAUJsV5DbnB5zOQir/nL37bSBXMfuEO5kv4EqSkDaFuVX0qCbHO76pBK/zdsbCQm8zkNFjYJItU2L5tOqXHPnuEf7Sc47UIBZ4WAQ2fLPjAo3CPfbEIoSbT1QX6WwYLRoXTlI7vSWkBxGTWHu4MIK++7QXByqXHmHVC3zIEvjwhy0CgYEA2oJrzfIvp68S2Qam/+PvdTzGnQUO0SooaUM06tHq4D4PwghImy1nrPNFS6O3Rm+OXRTUMhrjebcHK3Gpy0C+LV9YnNQqRTzFv/PMG3o6wmJaNzOtVwSQXhj3rfjZAn3uIDuOt8mdkrVJxh353EEbi3zksACn4so8ANzWWWG/LcY=
    ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt/gZfLmOUQYcB1tXT4zkbyXhJIZ+kwc9Vt0QJLPt0PAVVp4ytQXx8WoR0yVXv9Immo0VH6Tz7CMC3ecmSoxTNFwiEBVyQ3ypSSAn37tt0AUW5WJ4wgBB1Al/QRwcuLGLaCvsbj8z+fTm2cT06j3Lv9s8phBZJb18L8fHvZlNqAfjRuHt8oEfTAcaLj152V36MEFMIhI3+Kc03Q1X2CAnlUrzG+ZFmnDBSt+g6/CucTxXDyVPH+vqkZy1bGFN8NUQyFVdDvH0f7S2+wYe8Y8YpGvwGvYNs4H9QR7A+Y5IH+r0aSMhqGgOYLTsC16Wba0XDUo48Y7z2WBWElcSP3nSOQIDAQAB

xxl:
  job:
    admin: 
      addresses: http://192.168.5.129:8088/xxl-job-admin
    executor:
      appname: payresultnotify-job
      address: 
      ip: 
      port: 8989
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token