metadata:
- appName: ''
  dataId: content-api-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: swagger-dev.yaml
  desc: ''
  group: xuecheng-plus-common
  type: yaml
- appName: ''
  dataId: logging-dev.yaml
  group: xuecheng-plus-common
  type: yaml
- appName: ''
  dataId: auth-service-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: checkcode-dev.yaml
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: content-service-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: gateway-dev.yaml
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: learning-api-dev.yaml
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: learning-service-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: media-api-dev.yaml
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: media-service-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: message-service-dev.yaml
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: orders-api-dev.yaml
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: orders-service-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: search-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: system-api-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: system-service-dev.yaml
  desc: ''
  group: xuecheng-plus-project
  type: yaml
- appName: ''
  dataId: feign-dev.yaml
  desc: ''
  group: xuecheng-plus-common
  type: yaml
- appName: ''
  dataId: freemarker-config-dev.yaml
  desc: ''
  group: xuecheng-plus-common
  type: yaml
- appName: ''
  dataId: rabbitmq-dev.yaml
  desc: ''
  group: xuecheng-plus-common
  type: yaml
- appName: ''
  dataId: redis-dev.yaml
  group: xuecheng-plus-common
  type: yaml
